### ISSUE TITLE
HCMI Omics Build Issues

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#220]
Several issues for HCMI are appearing when running the omics build script. All are resulting from the 02-getHCMIData.py script when called through build_omics.sh. I'm not certain if these errors are independent of one another

**Polars Error**: aliquot_id not found, this occurs multiple times
```
Traceback (most recent call last):
  File "/usr/src/app/02-getHCMIData.py", line 779, in <module>
    main()
  File "/usr/src/app/02-getHCMIData.py", line 759, in main
    final_data = align_to_schema(combined_data,args.type,7500,args.samples)
  File "/usr/src/app/02-getHCMIData.py", line 452, in align_to_schema
    merged_chunk = merged_chunk.drop(["aliquot_id", "other_names"])
  File "/usr/local/lib/python3.9/site-packages/polars/dataframe/frame.py", line 7571, in drop
    return self.lazy().drop(*columns, strict=strict).collect(_eager=True)
  File "/usr/local/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 2050, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ColumnNotFoundError: "aliquot_id" not found
```

**Dataframe Manipulation Error**  - Not sure where or why this is occurring, but it occurs multiple times
```
	---> FAILED HERE RESOLVING THIS_NODE <---
DF ["other_names", "improve_sample_id", "entrez_id", "transcriptomics"]; PROJECT */6 COLUMNS; SELECTION: None
```

**Polars Error** - Data Type Mismatch
```
Traceback (most recent call last):                                             
  File "/usr/local/lib/python3.9/site-packages/polars/_utils/construction/series.py", line 308, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
TypeError: 'float' object cannot be converted to 'PyString'
```

**Polars Error** - Data type Mismatch. This occurs multiple times
```
Traceback (most recent call last):
  File "/usr/src/app/02-getHCMIData.py", line 779, in <module>
    main()
  File "/usr/src/app/02-getHCMIData.py", line 752, in main
    combined_data = map_and_combine(data_files, args.type, metadata, entrez_map_file)
  File "/usr/src/app/02-getHCMIData.py", line 289, in map_and_combine
    copy_call_series = copy_num(selected_df['copy_number'])
  File "/usr/src/app/02-getHCMIData.py", line 387, in copy_num
    return pl.Series([get_copy_call(a) for a in arr])
  File "/usr/local/lib/python3.9/site-packages/polars/series/series.py", line 289, in __init__
    self._s = sequence_to_pyseries(
  File "/usr/local/lib/python3.9/site-packages/polars/_utils/construction/series.py", line 293, in sequence_to_pyseries
    return _construct_series_with_fallbacks(
  File "/usr/local/lib/python3.9/site-packages/polars/_utils/construction/series.py", line 311, in _construct_series_with_fallbacks
    return PySeries.new_from_any_values(name, values, strict=strict)
TypeError: unexpected value while building Series of type String; found value of type Float64: NaN
```

**Comment by jjacobson95** [comment]
Not 100% fixed yet, but I believe these all stem from a polars version issue.
